name: Keep App Alive

on:
  schedule:
    # Har 12 ghante me run hoga
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -I -s --max-time 15 "https://starmedi-estimator.streamlit.app" || true
